version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: akuntansi-client-v1-dev
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_STORAGE_URL=${NEXT_PUBLIC_STORAGE_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3002:3002"
 
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name:  akuntansi-client-v1-production
    environment:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_STORAGE_URL=${NEXT_PUBLIC_STORAGE_URL}
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  node_modules: