version: "3.8"

services:
  frontend-akuntansi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akuntansi-client-v0
    ports:
      - "3031:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_STORAGE_URL=${NEXT_PUBLIC_STORAGE_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
