version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: akuntansi-client-v1-dev
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3001"
    env_file:
      - .env
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name:  akuntansi-client-v1-prodcution
    ports:
      - "3001:3001"
    env_file:
      - .env

volumes:
  node_modules: